language: rust
rust:
  - 1.18.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cd "${TRAVIS_BUILD_DIR}/examples/std";
    cargo build --verbose;
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then
      cargo build --verbose --no-default-features;
    fi
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then
      cd "${TRAVIS_BUILD_DIR}/examples/no_std";
      cargo build --verbose;
    fi
branches:
  only:
    - master
