[package]
name = "no_std"
version = "0.1.0"
authors = ["Joe Ranweiler <joe@lemma.co>"]

[dependencies]
libc = { version = "0.2.11", default-features = false }
liar = { path = "../..", default-features = false  }

[profile.dev]
# FIX: Linking fails on opt-level = 1.
opt-level = 2
